language: python
python:
    - "3.4"
    - "3.6"
services: sqlite3
env:
    matrix:
        - DJANGO=2.0 DB=sqlite3 SECRET_KEY="secretkey"
install:
    - "pip install -q Django==$DJANGO"
    - "pip install -q -r requirements.txt"
script:
- ./manage.py test
