language: python
python:
    - "3.6"
env:
    matrix:
        - DJANGO=2.0
branches:
    only:
        - deployment
before_install:
    - chmod +x manage.py
install:
    - "pip install -q Django==$DJANGO"
    - "pip install -q -r requirements.txt"
script:
    - SECRET_KEY="whatever" ./manage.py test
