# Generated by Django 2.1 on 2018-10-02 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('T1', 'Bug'), ('T2', 'Feature Request')], default='T1', max_length=2)),
                ('content', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('S1', 'Reviewing'), ('S2', 'To Do'), ('S3', 'Doing'), ('S4', 'Done'), ('S5', 'On Hold')], default='S1', max_length=2)),
                ('upvote_fund', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('upvote_user', models.ManyToManyField(blank=True, default=None, related_name='upvoted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
