# Generated by Django 2.1 on 2018-09-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('S1', 'Reviewing'), ('S2', 'To Do'), ('S3', 'Doing'), ('S4', 'Done'), ('S5', 'On Hold')], default='S1', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('T1', 'Bug'), ('T2', 'Feature Request')], default='T1', max_length=2),
        ),
    ]
