# Generated by Django 2.1 on 2018-09-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20180904_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
