# Generated by Django 2.1 on 2018-10-02 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('bug_tended', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(0)])),
                ('feature_tended', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(0)])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
