# Generated by Django 2.1.2 on 2018-10-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_progresslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='ticket',
            field=models.ForeignKey(limit_choices_to={'type': 'T2'}, on_delete=django.db.models.deletion.PROTECT, to='issuetracker.Ticket'),
        ),
    ]
