# Generated by Django 2.1 on 2018-09-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuetracker', '0005_auto_20180905_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='upvote',
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvote_fund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvote_user',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fund',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issuetracker.Ticket'),
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
