# Generated by Django 2.1 on 2018-09-23 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_auto_20180908_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
